name: Deploy to Webempresa

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Asegura que se obtenga todo el historial de commits

      - name: Set up Git
        run: git config --global user.email "youremail@example.com" && git config --global user.name "Your Name"

      - name: Get changed files
        id: changed-files
        run: |
          # Obtener la lista de archivos modificados entre el commit actual y el anterior
          git diff --name-only HEAD~1 HEAD > changed-files.txt
          # Si no hay cambios, salir temprano
          if [ ! -s changed-files.txt ]; then
            echo "No changes detected. Exiting."
            exit 0
          fi
          # Mostrar los archivos modificados para debug
          cat changed-files.txt
        continue-on-error: true

      - name: Upload changed files to Webempresa server using lftp
        if: success() # Solo se ejecuta si la tarea anterior no falló
        run: |
          # Instalar lftp
          sudo apt-get install -y lftp

          # Conectar al servidor FTP y subir solo los archivos modificados
          lftp -u "desarrollo@jessica2-cp27.wordpresstemporal.com", "arielDesarrollo2024" ftps://178.33.115.23 <<EOF
          set ftp:ssl-allow yes
          set mirror:use-pget-n 5
          set mirror:parallel-directories 3
          mirror --only-newer --verbose --include-glob "changed-files.txt" . /remote/target/directory/
          quit
          EOF
