name: Deploy to Webempresa

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Sync files to Webempresa server via SFTP
        uses: appleboy/scp-action@master
        with:
          host: "178.33.115.23" # IP del servidor
          username: "desarrollo@jessica2-cp27.wordpresstemporal.com" # Usuario de FTP
          password: "arielDesarrollo2024" # Contraseña de FTP
          port: 22 # Puerto estándar para SFTP
          source: "./" # Directorio local del repositorio
          target: "/public_html/desarrollo/" # Directorio en el servidor donde quieres desplegar los archivos
