name: Deploy to WordPress

on:
  push:
    branches:
      - master # Cambia esto si usas otra rama

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4" # Cambia esto a la versión de PHP que necesites

      - name: Install Composer dependencies
        run: composer install --no-dev

      - name: Deploy to WordPress
        env:
          WORDPRESS_HOST: ${{ secrets.WORDPRESS_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
        run: |
          # Configurar SSH
          echo "${{ secrets.SSH_KEY }}" > wordpress_key
          chmod 600 wordpress_key

          # Asegúrate de tener WP-CLI en el servidor
          ssh -i wordpress_key -o StrictHostKeyChecking=no $SSH_USER@$WORDPRESS_HOST "
            curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar &&
            chmod +x wp-cli.phar &&
            sudo mv wp-cli.phar /usr/local/bin/wp
          "

          # Ejecutar WP-CLI en el servidor
          ssh -i wordpress_key -o StrictHostKeyChecking=no $SSH_USER@$WORDPRESS_HOST "
            sudo wp core download --path=/var/www/html &&
            sudo wp config create --dbname=$DB_NAME --dbuser=$DB_USER --dbpass=$DB_PASSWORD --dbhost=$DB_HOST --path=/var/www/html &&
            sudo wp db import /path/to/your/dump.sql --path=/var/www/html &&
            sudo wp plugin activate plugin-slug --path=/var/www/html
          "

      - name: Clean up
        run: rm -f wordpress_key
